import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import generateWorksheet from "@/util/generateWorksheet";

const Home: NextPage = () => {
  const [additionWorksheetSettings, setAdditionWorksheetSettings] =
    useState<IAdditionWorksheetSettings>({
      numberOfDigits: {
        min: 2,
        max: 2,
      },
      numberOfItems: 15,
      numberOfOperands: 3,
    });
  const [additionWorksheetItems, setAdditionWorksheetItems] = useState<
    IAdditionWorksheetItem[]
  >([
    {
      operands: [1, 2],
      correctAnswer: 3,
    },
  ]);

  useEffect(() => {}, [additionWorksheetSettings]);

  function handleGenerateWorksheet() {
    setAdditionWorksheetItems(generateWorksheet(additionWorksheetSettings));
  }
  return (
    <div>
      <Head>
        <title>Solvit - Deliberate Math Practice Trainer!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <input type="range" />
        </div>
        <div>
          {additionWorksheetItems.map((worksheetItem, i) => (
            <div key={i}>
              {`${i + 1}) `}
              {worksheetItem.operands.map((operandItem, i) => (
                <span key={i}>
                  <span>{operandItem}</span>
                  {i < worksheetItem.operands.length - 1 && <span>+</span>}
                </span>
              ))}
              ={" "}
              <span className="text-transparent hover:text-white">
                {worksheetItem.correctAnswer}
              </span>
            </div>
          ))}
        </div>
        <button onClick={handleGenerateWorksheet}>Generate Worksheet</button>
      </main>

      <footer>Footer</footer>
    </div>
  );
};

export default Home;
